# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b62512baa30d139dc0e85a34be0a0d5835e5d9205fc57c5dfaf3a4ff9d3386d56abc1688c672ed5c6c6504c26e4f81633c2256ea4e650b4ce09afdff28c3b8cf

test:
  secret_key_base: 13600c712bd73bffc40fdc882d2144f55aeef55a7e5e959990136723af58289dc69397cae4512d9b96166f4afa06dfdf5d7434df04a9479c503e8972ac5d2b5f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
